# Etapa de build com Java 21
FROM eclipse-temurin:21-jdk AS build

WORKDIR /app

# Copia o projeto para dentro da imagem
COPY . .

# Usa cache do Maven
RUN --mount=type=cache,target=/root/.m2 \
    ./mvnw -B -DskipTests clean install -DoutputFile=target/mvn-dependency-list.log

# Etapa final: runtime com Java 21
FROM eclipse-temurin:21-jdk

WORKDIR /app

COPY --from=build /app/target/quarkus-app/lib/ /app/lib/
COPY --from=build /app/target/quarkus-app/*.jar /app/
COPY --from=build /app/target/quarkus-app/app/ /app/app/
COPY --from=build /app/target/quarkus-app/quarkus/ /app/quarkus/

CMD ["java", "-jar", "/app/quarkus-run.jar"]
